name: toko_rajawali
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mobile_scanner: ^5.1.0 # Library kamera aktif
  sqflite: ^2.3.0
  path: ^1.9.0
  google_fonts: ^6.2.1
  provider: ^6.1.5+1
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  sqflite_common_ffi_web: ^1.1.1
  intl: ^0.20.2
  url_launcher: ^6.2.0
  shared_preferences: ^2.2.2
  blue_thermal_printer: ^1.1.5
  esc_pos_utils: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: assets/logo.png

flutter:
  uses-material-design: true